parameters:
    pim_catalog.generator.completeness.class: Pim\Component\Catalog\Completeness\CompletenessGenerator
    pim_catalog.generator.required_values.class: Pim\Component\Catalog\Completeness\RequiredValuesGenerator
    pim_catalog.calculator.completeness.class: Pim\Component\Catalog\Completeness\CompletenessCalculator
    pim_catalog.calculator.missing_required_attributes.class: Pim\Component\Catalog\Completeness\MissingRequiredAttributesCalculator

services:
    pim_catalog.generator.completeness:
        class: '%pim_catalog.generator.completeness.class%'
        arguments:
            - '@pim_catalog.query.product_query_builder_factory'
            - '@pim_catalog.calculator.completeness'

    pim_catalog.generator.required_values:
        class: '%pim_catalog.generator.required_values.class%'
        arguments:
            - '@pim_catalog.factory.value'

    pim_catalog.calculator.completeness:
        class: '%pim_catalog.calculator.completeness.class%'
        arguments:
            - '@pim_catalog.repository.cached_channel'
            - '@pim_catalog.repository.cached_locale'
            - '@pim_catalog.calculator.missing_required_attributes'
            - '@pim_catalog.generator.required_values'
            - '%pim_catalog.entity.completeness.class%'

    pim_catalog.calculator.missing_required_attributes:
        class: '%pim_catalog.calculator.missing_required_attributes.class%'
        arguments:
            - '@pim_catalog.completeness.checker'
            - '@pim_catalog.repository.cached_channel'
            - '@pim_catalog.repository.cached_locale'
